<?php 
/************************************************
 Sphider-plus version 3.2014a Database configuration file.

 > > >  DO NOT EDIT THIS FILE. < < < 

Any changes must be done by Admin's database settings. 
*************************************************/



/******************************* Check for forbidden direct access ************************************/

    if (!defined('_SECURE')) die ("No direct access to database file");



// Count of successfully created databases
$db_count = "1";

// Currently activated Admin database
$dba_act = "1";

// Currently activated Search User database
$dbu_act = "1";

// Currently activated Suggest URL User database
$dbs_act = "1";

// Activated databases that should deliver search results
$db1_slv = "1";
$db2_slv = "0";
$db3_slv = "0";
$db4_slv = "0";
$db5_slv = "0";



/*********************** 
Database 1 settings
***********************/

// Name of database
$database1 = 'sphider_plus';

// MySQL User
$mysql_user1 = 'root';

// MySQL Password
$mysql_password1 = 'root';

// MySQL Host
$mysql_host1 = 'localhost';

// Prefix for tables
$mysql_table_prefix1 = 'search1_';

// Status of database
$db1_set = '1';

// Activation status
$db1_act = '';


/*********************** 
Database 2 settings
***********************/

// Name of database
$database2 = '';

// MySQL User
$mysql_user2 = '';

// MySQL Password
$mysql_password2 = '';

// MySQL Host
$mysql_host2 = '';

// Prefix for tables
$mysql_table_prefix2 = '';

// Status of database
$db2_set = '0';

// Activation status
$db2_act = '';


/*********************** 
Database 3 settings
***********************/

// Name of database
$database3 = '';

// MySQL User
$mysql_user3 = '';

// MySQL Password
$mysql_password3 = '';

// MySQL Host
$mysql_host3 = '';

// Prefix for tables
$mysql_table_prefix3 = '';

// Status of database
$db3_set = '0';

// Activation status
$db3_act = '';


/*********************** 
Database 4 settings
***********************/

// Name of database
$database4 = '';

// MySQL User
$mysql_user4 = '';

// MySQL Password
$mysql_password4 = '';

// MySQL Host
$mysql_host4 = '';

// Prefix for tables
$mysql_table_prefix4 = '';

// Status of database
$db4_set = '0';

// Activation status
$db4_act = '';


/*********************** 
Database 5 settings
***********************/

// Name of database
$database5 = '';

// MySQL User
$mysql_user5 = '';

// MySQL Password
$mysql_password5 = '';

// MySQL Host
$mysql_host5 = '';

// Prefix for tables
$mysql_table_prefix5 = '';

// Status of database
$db5_set = '0';

// Activation status
$db5_act = '';

?>
